# Generated by Django 3.0.6 on 2024-09-24 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(db_column='ID_Familia', primary_key=True, serialize=False)),
                ('nombre_familia', models.CharField(db_column='Nombre_Familia', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(db_column='ID_Grupo', primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(db_column='Nombre_Grupo', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(db_column='ID_producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(db_column='Nombre_Producto', max_length=255)),
                ('id_familia', models.ForeignKey(db_column='ID_Familia', on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.Familia')),
                ('id_grupo', models.ForeignKey(db_column='ID_Grupo', on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.Grupo')),
            ],
        ),
    ]
